/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : I2CSPY1.h
**     Project     : Ascensor
**     Processor   : MKL46Z256VMC4
**     Component   : I2CSpy
**     Version     : Component 01.009, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-03-26, 18:53, # CodeGen: 68
**     Abstract    :
**          This component implements a utility to inspect devices on the I2C bus.
**     Settings    :
**          Component name                                 : I2CSPY1
**          I2C                                            : GI2C1
**          Default Address                                : 0x1D
**          Default Address Size                           : 1
**          Default Bytes per Line                         : 8
**          Shell                                          : Enabled
**            Shell                                        : CLS1
**            Utility                                      : UTIL1
**     Contents    :
**         Init             - byte I2CSPY1_Init(void);
**         Deinit           - void I2CSPY1_Deinit(void);
**         SetDeviceAddress - byte I2CSPY1_SetDeviceAddress(byte addr);
**         GetDeviceAddress - byte I2CSPY1_GetDeviceAddress(void);
**         SetAddressSize   - byte I2CSPY1_SetAddressSize(byte size);
**         SetBytesPerLine  - byte I2CSPY1_SetBytesPerLine(byte nofBytesPerLine);
**         ReadRegData      - byte I2CSPY1_ReadRegData(dword addr, byte *data, word dataSize);
**         WriteRegData     - byte I2CSPY1_WriteRegData(dword addr, byte *data, word dataSize);
**         ParseCommand     - byte I2CSPY1_ParseCommand(const unsigned char *cmd, bool *handled, const...
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2013, all rights reserved.
**     Web/Blog: www.mcuoneclipse.com
**     This an open source software implementing software using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file I2CSPY1.h
** @version 01.00
** @brief
**          This component implements a utility to inspect devices on the I2C bus.
*/         
/*!
**  @addtogroup I2CSPY1_module I2CSPY1 module documentation
**  @{
*/         

#ifndef __I2CSPY1_H
#define __I2CSPY1_H

/* MODULE I2CSPY1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "GI2C1.h"
#include "CLS1.h"
#include "UTIL1.h"

#include "Cpu.h"


#define I2CSPY1_PARSE_COMMAND_ENABLED  1  /* set to 1 if method ParseCommand() is present, 0 otherwise */


byte I2CSPY1_Init(void);
/*
** ===================================================================
**     Method      :  I2CSPY1_Init (component I2CSpy)
**     Description :
**         Initialization method
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void I2CSPY1_Deinit(void);
/*
** ===================================================================
**     Method      :  I2CSPY1_Deinit (component I2CSpy)
**     Description :
**         Deinitialization method
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

byte I2CSPY1_SetDeviceAddress(byte addr);
/*
** ===================================================================
**     Method      :  I2CSPY1_SetDeviceAddress (component I2CSpy)
**     Description :
**         Sets the I2C Device address to be used
**     Parameters  :
**         NAME            - DESCRIPTION
**         addr            - I2C 7bit address
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

byte I2CSPY1_SetAddressSize(byte size);
/*
** ===================================================================
**     Method      :  I2CSPY1_SetAddressSize (component I2CSpy)
**     Description :
**         Specifies the address size of the I2C device memory
**     Parameters  :
**         NAME            - DESCRIPTION
**         size            - Either 1 (8bit), 2 (16bit), 3 (24bit),
**                           or 4 (32bit)
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

byte I2CSPY1_SetBytesPerLine(byte nofBytesPerLine);
/*
** ===================================================================
**     Method      :  I2CSPY1_SetBytesPerLine (component I2CSpy)
**     Description :
**         Sets the number of bytes per line for the Dump shell command
**     Parameters  :
**         NAME            - DESCRIPTION
**         nofBytesPerLine - Number of bytes
**                           per line
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void GI2C1_OnRequestBus(void);

void GI2C1_OnReleaseBus(void);

byte I2CSPY1_ReadRegData(dword addr, byte *data, word dataSize);
/*
** ===================================================================
**     Method      :  I2CSPY1_ReadRegData (component I2CSpy)
**     Description :
**         Reads data starting from a register address from the current
**         device
**     Parameters  :
**         NAME            - DESCRIPTION
**         addr            - Device address
**       * data            - Pointer to data buffer where read data
**                           is stored
**         dataSize        - size of data buffer in bytes
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

byte I2CSPY1_WriteRegData(dword addr, byte *data, word dataSize);
/*
** ===================================================================
**     Method      :  I2CSPY1_WriteRegData (component I2CSpy)
**     Description :
**         Writes data starting from a register address to the current
**         device
**     Parameters  :
**         NAME            - DESCRIPTION
**         addr            - Address in device
**       * data            - Pointer to data to write
**         dataSize        - Size of data in bytes
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

byte I2CSPY1_ParseCommand(const unsigned char *cmd, bool *handled, const CLS1_StdIOType *io);
/*
** ===================================================================
**     Method      :  I2CSPY1_ParseCommand (component I2CSpy)
**     Description :
**         Shell Command Line parser
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command string
**       * handled         - Pointer to variable which tells if
**                           the command has been handled or not
**         io              - Pointer to I/O structure
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

byte I2CSPY1_GetDeviceAddress(void);
/*
** ===================================================================
**     Method      :  I2CSPY1_GetDeviceAddress (component I2CSpy)
**     Description :
**         Returns the current I2C Device address used
**     Parameters  : None
**     Returns     :
**         ---             - 7bit Device Address
** ===================================================================
*/

/* END I2CSPY1. */

#endif
/* ifndef __I2CSPY1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
