/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : TimeDate.h
**     Project     : Ascensor
**     Processor   : MKL46Z256VMC4
**     Component   : GenericTimeDate
**     Version     : Component 01.027, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-11-03, 11:35, # CodeGen: 81
**     Abstract    :
**         Software date/time module.
**     Settings    :
**          Component name                                 : TimeDate
**          Critical Section                               : CS1
**          Tick Time (ms)                                 : 10
**          RTOS                                           : Disabled
**          Shell                                          : Disabled
**          Initialization                                 : Enabled
**            Init in startup                              : yes
**            Date                                         : 2014-05-16
**            Time                                         : 15:35:56
**     Contents    :
**         AddTick     - void TimeDate_AddTick(void);
**         AddTicks    - void TimeDate_AddTicks(uint16_t nofTicks);
**         TicksToTime - uint8_t TimeDate_TicksToTime(uint32_t ticks, TIMEREC *Time);
**         TimeToTicks - uint8_t TimeDate_TimeToTicks(TIMEREC *Time, uint32_t *ticks);
**         SetTime     - uint8_t TimeDate_SetTime(uint8_t Hour, uint8_t Min, uint8_t Sec, uint8_t...
**         GetTime     - uint8_t TimeDate_GetTime(TIMEREC *Time);
**         SetDate     - uint8_t TimeDate_SetDate(uint16_t Year, uint8_t Month, uint8_t Day);
**         GetDate     - uint8_t TimeDate_GetDate(DATEREC *Date);
**         Init        - void TimeDate_Init(void);
**         DeInit      - void TimeDate_DeInit(void);
**
**     (c) Copyright Freescale Semiconductor, 2014
**     http: www.freescale.com
**     Source code is based on the original TimeDate Processor Expert component.
** ###################################################################*/
/*!
** @file TimeDate.h
** @version 01.00
** @brief
**         Software date/time module.
*/         
/*!
**  @addtogroup TimeDate_module TimeDate module documentation
**  @{
*/         

#ifndef __TimeDate_H
#define __TimeDate_H

/* MODULE TimeDate. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "CS1.h"
#define TimeDate_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */

#ifndef __BWUserType_TIMEREC
#define __BWUserType_TIMEREC
  typedef struct {                     /* It contains actual number of hours, minutes, seconds and hundreth of seconds. */
    uint8_t Hour;                      /* hours (0 - 23) */
    uint8_t Min;                       /* minutes (0 - 59) */
    uint8_t Sec;                       /* seconds (0 - 59) */
    uint8_t Sec100;                    /* hundredth of seconds (0 - 99) */
  } TIMEREC;
#endif
#ifndef __BWUserType_DATEREC
#define __BWUserType_DATEREC
  typedef struct {                     /* It contains actual year, month, and day description. */
    uint16_t Year;                     /* years (1998 - 2099) */
    uint8_t Month;                     /* months (1 - 12) */
    uint8_t Day;                       /* days (1 - 31) */
  } DATEREC;
#endif

#include "Cpu.h"




uint8_t TimeDate_SetTime(uint8_t Hour, uint8_t Min, uint8_t Sec, uint8_t Sec100);
/*
** ===================================================================
**     Method      :  TimeDate_SetTime (component GenericTimeDate)
**     Description :
**         This method sets a new actual time.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Hour            - Hours (0 - 23)
**         Min             - Minutes (0 - 59)
**         Sec             - Seconds (0 - 59)
**         Sec100          - Hundredth of seconds (0 - 99)
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void TimeDate_AddTick(void);
/*
** ===================================================================
**     Method      :  TimeDate_AddTick (component GenericTimeDate)
**     Description :
**         Needs to be called periodically by the application to
**         increase the time tick count.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

uint8_t TimeDate_GetTime(TIMEREC *Time);
/*
** ===================================================================
**     Method      :  TimeDate_GetTime (component GenericTimeDate)
**     Description :
**         This method returns current time.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - Pointer to the structure TIMEREC. It
**                           contains actual number of hours, minutes,
**                           seconds and hundredth of seconds.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t TimeDate_SetDate(uint16_t Year, uint8_t Month, uint8_t Day);
/*
** ===================================================================
**     Method      :  TimeDate_SetDate (component GenericTimeDate)
**     Description :
**         This method sets a new actual date.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Year            - Years (16-bit unsigned integer)
**         Month           - Months (8-bit unsigned integer)
**         Day             - Days (8-bit unsigned integer)
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t TimeDate_GetDate(DATEREC *Date);
/*
** ===================================================================
**     Method      :  TimeDate_GetDate (component GenericTimeDate)
**     Description :
**         This method returns current date.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Date            - Pointer to DATEREC
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void TimeDate_Init(void);
/*
** ===================================================================
**     Method      :  TimeDate_Init (component GenericTimeDate)
**     Description :
**         Initialization method
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void TimeDate_DeInit(void);
/*
** ===================================================================
**     Method      :  TimeDate_DeInit (component GenericTimeDate)
**     Description :
**         Deinitializes the driver.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void TimeDate_AddTicks(uint16_t nofTicks);
/*
** ===================================================================
**     Method      :  TimeDate_AddTicks (component GenericTimeDate)
**     Description :
**         Same as AddTick(), but multiple ticks can be added in one
**         step.
**     Parameters  :
**         NAME            - DESCRIPTION
**         nofTicks        - Number of ticks to be added
**     Returns     : Nothing
** ===================================================================
*/

uint8_t TimeDate_TicksToTime(uint32_t ticks, TIMEREC *Time);
/*
** ===================================================================
**     Method      :  TimeDate_TicksToTime (component GenericTimeDate)
**     Description :
**         Transforms ticks into time information
**     Parameters  :
**         NAME            - DESCRIPTION
**         ticks           - 
**       * Time            - Pointer where to store the time
**                           information
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t TimeDate_TimeToTicks(TIMEREC *Time, uint32_t *ticks);
/*
** ===================================================================
**     Method      :  TimeDate_TimeToTicks (component GenericTimeDate)
**     Description :
**         Transforms time information into ticks
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - Pointer where to time information
**       * ticks           - Pointer to where to store the ticks
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

/* END TimeDate. */

#endif
/* ifndef __TimeDate_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
